# Generated by Django 5.0 on 2024-01-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name of the Theatre')),
                ('owner', models.CharField(max_length=512, verbose_name='Name of the Owner')),
                ('screens', models.IntegerField(null=True, verbose_name='Total Screens')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=1024, verbose_name='Theatre Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZIP Code')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('opening_time', models.TimeField(null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(null=True, verbose_name='Closing Time')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='theatre_logos/', verbose_name='Theatre Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('directions_link', models.URLField(blank=True, max_length=512, null=True, verbose_name='Directions Link')),
            ],
        ),
    ]
