# Generated by Django 5.0 on 2024-01-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theatre',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Theatres'},
        ),
    ]
