# Generated by Django 5.0 on 2023-12-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name of the Movie')),
                ('director', models.CharField(max_length=512, verbose_name='Name of the Director')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publish the Movie')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('release_date', models.DateField()),
                ('total_time', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_on'],
            },
        ),
    ]
