# Generated by Django 5.0 on 2023-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_is_published_alter_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='total_time',
        ),
        migrations.AddField(
            model_name='movie',
            name='total_time_minutes',
            field=models.IntegerField(null=True, verbose_name='Total Time (in minutes)'),
        ),
    ]
