# Generated by Django 5.0 on 2023-12-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_total_time_movie_total_time_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters/'),
        ),
    ]
