# Generated by Django 5.0 on 2024-01-03 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name of the Screen')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=512, verbose_name='Status of the Screen')),
                ('screen_type', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=512, verbose_name='Type of the Screen')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_3d_capable', models.BooleanField(default=False, verbose_name='3D Capability')),
                ('is_wheelchair_accessible', models.BooleanField(default=False, verbose_name='Wheelchair Accessibility')),
                ('audio_type', models.CharField(max_length=512, verbose_name='Audio type')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Last Maintenance Date')),
                ('price_category', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20, verbose_name='Price Category')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre', verbose_name='Name of the Theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, verbose_name='Seat Number')),
                ('seat_type', models.CharField(max_length=20, verbose_name='Type of Sear')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screen.screen', verbose_name='Screen')),
            ],
        ),
    ]
