# Generated by Django 5.0 on 2024-01-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'verbose_name_plural': 'Screens'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name_plural': 'Seats'},
        ),
    ]
