# Generated by Django 5.0 on 2024-01-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_alter_screen_options_alter_seat_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
