# Generated by Django 5.0 on 2024-01-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0004_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, verbose_name='Seat Number')),
                ('seat_type', models.CharField(choices=[('normal', 'Normal'), ('recliner', 'Recliner')], max_length=20, verbose_name='Type of Seat')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screen.block', verbose_name='Block')),
            ],
            options={
                'verbose_name_plural': 'Screens | Seats',
            },
        ),
    ]
