# Generated by Django 5.0 on 2024-01-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0005_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_type',
        ),
    ]
