# Generated by Django 5.0 on 2024-01-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0006_remove_seat_seat_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('block', 'seat_number')},
        ),
    ]
